#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# 运行 ESLint 检查
echo 开始提交代码了...
# 检查lint
npm run lint --silent 
echo 提交代码前需要先进行单元测试
# 执行测试
npm run test
echo 测试完成
npm run lint:style --silent
# git add .
npm run commitlint